version: '3.8'

services:
  king-15:
    image: david-15
    build: .
    ports:
      - '6009:3000'
    environment:
      - MONGO_URI:'mongodb://127.0.0.1:27017/hostel'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
